//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode
// http://embedXcode.weebly.com
//
// Project 		robot
//
// Created by 	Tarun Chaudhry, 5/6/15 12:00 AM
//              Tarun Chaudhry
//
// Copyright 	© Tarun Chaudhry, 2015
// Licence 		<#license#>
//
// See 			robot.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN robot.ino
// ----------------------------------
//
// Last update: Apr 15, 2015 release 280

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
#if defined(ENERGIA)
// ============================================================================= LaunchPad MSP430, Stellaris and Tiva, Experimeter Board FR5739 specific
// ----------------------------------------------------------------------------- LaunchPad MSP430 and Experimeter Board FR5739 specific

//#include <Energia.h>

int main(void)
{
	init();
    
	setup();
    
	for (;;) {
		loop();
//		if (serialEventRun) serialEventRun();
	}
    
	return 0;
}

#endif                                                                          // Energia

// Sketch
#include "robot.ino"


#endif                                                                          // end embedXcode

